// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvjmxcovosgkeufwerlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2am14Y292b3Nna2V1ZndlcmxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODY3MjgsImV4cCI6MjA2NjM2MjcyOH0.2CdGF9UHvXsvMsGyN6HtYaue2nPoizTuaysycRP4_aI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);